# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170120_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_measure',
            name='sensor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.sensor'),
        ),
    ]
