# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sensor_measure_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_measure',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sensor'),
        ),
    ]
