# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170120_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='user',
            new_name='nutzer',
        ),
    ]
