# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170121_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='nutzer',
            new_name='user',
        ),
    ]
