# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170121_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='user',
            new_name='kunde',
        ),
    ]
