# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170121_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='heater',
            field=models.CharField(default='', max_length=100),
        ),
    ]
